apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-cluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            kyverno: 'true'
  template:
    metadata:
      # name is the name of the kubernetes cluster as selected by the spec above
      name: 'vault'
    spec:
      destination:
        # server is the url of the cluster as selected by the spec above
        server: '{{server}}'
        namespace: vault
      project: default
      source:
        chart: vault
        repoURL: https://helm.releases.hashicorp.com
        targetRevision: 0.28.1
        helm:
          valuesObject:
            server:
              ingress:
                enabled: true
                ingressClassName: 'nginx'
                tls:
                  - hosts:
                      - "vault-{{metadata.labels.vclusterName}}.{{metadata.labels.domain}}"
                hosts:
                  - host: "vault-{{metadata.labels.vclusterName}}.{{metadata.labels.domain}}"
                    paths:
                      - /
            ui:
              enabled: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true
        retry:
          limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 20s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 3m
