apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: api-framework-dev
  namespace: loft-p-api-framework
spec:
  owner:
    user: admin
  templateRef:
    name: vcluster-pro-template
  clusterRef:
    cluster: loft-cluster