apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: dev-REPLACE_LOFT_CLUSTER_NAME
  namespace: loft-p-sales-demos
spec:
  owner:
    team: loft-admins
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    pro:
      enabled: true
    helmRelease:
      chart: {}
      values: |-
        sync:
          ingresses:
            enabled: true
        coredns:
          integrated: true
    accessPoint:
      ingress:
        enabled: true
    spaceTemplate:
      metadata: {}
  clusterRef:
    cluster: REPLACE_CLUSTER
    namespace: loft-sales-demos-v-dev-REPLACE_LOFT_CLUSTER_NAME
    virtualCluster: dev-REPLACE_LOFT_CLUSTER_NAME