kind: Project
apiVersion: management.loft.sh/v1
metadata:
  name: api-framework
spec:
  displayName: API Framework
  owner:
    team: loft-admins
  quotas:
    project:
      count/virtualclusterinstances.active: '15'
    user:
      count/virtualclusterinstances: '4'
  allowedClusters:
    - name: loft-cluster
    - name: vcluster-test-bis
  allowedTemplates:
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: vcluster-pro-template
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: preview-template
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: vcluster-platform-demo-generator
  requireTemplate: {}
  members:
    - kind: Team
      group: storage.loft.sh
      name: api-framework
      clusterRole: loft-management-project-user
  access:
    - name: loft-admin-access
      verbs:
        - get
        - update
        - patch
        - delete
      subresources:
        - '*'
      users:
        - admin
    - name: loft-access
      verbs:
        - get
      subresources:
        - members
        - clusters
        - templates
        - chartinfo
        - charts
      teams:
        - api-framework
  argoCD:
    enabled: true
    cluster: loft-cluster
    namespace: argocd
    project:
      enabled: true
    sso:
      enabled: true
      host: https://argocd-vcluster-platform.test.deepseadevops.net/
      assignedRoles:
        - role:admin
---
kind: Project
apiVersion: management.loft.sh/v1
metadata:
  name: auth-core
spec:
  displayName: Auth Core
  description: AuthN and AuthZ core components built on top of the API Framework.
  owner:
    team: loft-admins
  quotas:
    project:
      count/virtualclusterinstances.active: '20'
  allowedClusters:
    - name: '*'
  allowedTemplates:
    - kind: DevPodWorkspaceTemplate
      group: storage.loft.sh
      name: '*'
    - kind: SpaceTemplate
      group: storage.loft.sh
      name: '*'
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: vcluster-pro-template
  requireTemplate: {}
  members:
    - kind: Team
      group: storage.loft.sh
      name: auth-core
      clusterRole: loft-management-project-user
  access:
    - name: loft-admin-access
      verbs:
        - get
        - update
        - patch
        - delete
      subresources:
        - '*'
      users:
        - kurtmadel
    - name: loft-access
      verbs:
        - get
      subresources:
        - members
        - clusters
        - templates
        - chartinfo
        - charts
      teams:
        - auth-core
  argoCD:
    enabled: true
    cluster: loft-cluster
    namespace: argocd
    sso:
      enabled: true
      host: https://argocd-vcluster-platform.test.deepseadevops.net/
      assignedRoles:
        - role:admin