apiVersion: management.loft.sh/v1
kind: VirtualClusterTemplate
metadata:
  name: vcluster-pro-template
  labels:
    app.kubernetes.io/instance: loft-configuration
spec:
  displayName: Virtual Cluster Pro Template
  description: This virtual cluster template deploys a vCluster.Pro virtual cluster
  owner:
    team: loft-admins
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    pro: {}
    helmRelease:
      chart: {}
      values: |-
        # Below you can configure the virtual cluster
        isolation:
          enabled: false

        vcluster:
          image: rancher/k3s:{{ .Values.k8sVersion }}-k3s1

        sync:
          ingresses:
            enabled: true

        coredns:
          integrated: true

        # Checkout https://vcluster.com/pro/docs/ for more config options
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  versions:
    - template:
        metadata: {}
        instanceTemplate:
          metadata:
            labels:
              environment: '{{ .Values.environment }}'
              team: '{{ .Values.loft.project }}'
        pro:
          enabled: true
        helmRelease:
          chart: 
            version: v0.18.0
          values: |-
            # Below you can configure the virtual cluster
            isolation:
              enabled: false

            # Use an embedded managed etcd server instead of using the default SQLite backend
            embeddedEtcd:
              enabled: true

            vcluster:
              image: rancher/k3s:{{ .Values.k8sVersion }}-k3s1

            sync:
              ingresses:
                enabled: true

            coredns:
              integrated: true

            # Checkout https://vcluster.com/pro/docs/ for more config options
        accessPoint:
          ingress: {}
        spaceTemplate:
          metadata: {}
      parameters:
        - variable: k8sVersion
          label: k8sVersion
          description: Please select Kubernetes version
          options:
            - v1.28.3
            - v1.28.2
            - v1.27.5
            - v1.26.9
          defaultValue: v1.27.5
        - variable: environment
          label: Deployment Environment
          description: Environment for deployments
          options:
            - dev
            - staging
            - production
          defaultValue: dev
      version: 1.0.0
    - template:
        metadata: {}
        instanceTemplate:
          metadata: {}
        pro:
          enabled: true
        helmRelease:
          chart: {}
          values: |-
            # Below you can configure the virtual cluster
            isolation:
              enabled: false

            sync:
              ingresses:
                enabled: true

            coredns:
              integrated: true

            # Checkout https://vcluster.com/pro/docs/ for more config options
        accessPoint:
          ingress: {}
        spaceTemplate:
          metadata: {}
      version: 0.0.0
  access:
    - verbs:
        - '*'
      subresources:
        - '*'
      users:
        - admin
---
kind: VirtualClusterTemplate
apiVersion: management.loft.sh/v1
metadata:
  name: preview-template
spec:
  displayName: vCluster.Pro Preview Template
  template:
    metadata:
      labels:
        loft.sh/import-argocd: 'true'
      annotations:
        sleepmode.loft.sh/delete-after: '72000'
        loft.sh/require-ingress-authentication: 'true'
        sleepmode.loft.sh/sleep-after: '600'
    objects: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: preview-hello-world-app
      ---
      apiVersion: v1
      kind: Secret
      metadata:
        name: ghcr-login-secret
        namespace: preview-hello-world-app
        labels:
          loft.sh/project-secret-name: ghcr-login-secret
      data:
        .dockerconfigjson: e30K
      type: kubernetes.io/dockerconfigjson
    access:
      rules:
        - teams:
            - loft-admins
          clusterRole: cluster-admin
    pro:
      enabled: true
    helmRelease:
      chart: 
        version: v0.18.0
      values: |-
        sync:
          ingresses:
            enabled: true
        # Use an embedded managed etcd server instead of using the default SQLite backend
        embeddedEtcd:
          enabled: true
        isolation:
          enabled: true
          networkPolicy:
            enabled: false
        coredns:
          integrated: true
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  access:
    - verbs:
        - '*'
      subresources:
        - '*'
      users:
        - admin

