apiVersion: v1
kind: Secret
metadata:
  name: loft-demo-org-cred
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
data:
  githubAppID: REPLACE_APP_ID
  githubAppInstallationID: REPLACE_INSTALL_ID
  githubAppPrivateKey: REPLACE_APP_PRIVATE_KEY
  url: aHR0cHM6Ly9naXRodWIuY29tL2xvZnQtZGVtb3MK
  type: aGVsbQ==
type: Opaque